site:
  title: Red Hat OpenShift AI - Models as a Service
  start_page: maas::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
