:time_estimate: 5

= Lab: Section Title

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Section objective.

WARNING: Not started  yet.

== Before you begin

Describe requirements, such as customer portal accounts, Red Hat Developer free sub, already configured machines, access to container registries, etc.

== Instructions

High-level summary of what you will perform in this lab, but more detailed than the objective.

1. Task or outcome.

.. Something to do, using a graphical or web UI.
Click menu:Save As[] to save your work.

.. More things to do

2. Task or outcome.

.. Something to do, using a shell.
+
[source,console,subs="verbatim,quotes"]
--
$ *command --options fixed-arguments _variable-arguments_*
output of the command
highlight *something* in the output
--


.. More things to do.
Press kbd:[Ctrl+C] to interrupt.

Summary of what you acomplished.

== What's next

In the next section/chapter, you will... Summary of the next section or chapter, and how it connects to what you just performed.