= Course Title
:navtitle: Home

== Goal

Course goal.

== Objectives

On completing this course, you should be able to:

* Learning objective #1

* Learning objective #2

* Learning objective #3

== Audience

Who should take this course.

== Prerequisites

This course assumes that you have the following experience:

* Familiarity with task, concept, or technology.

* Familiarity with task, concept, or technology.

* Familiarity with task, concept, or technology.

It's recommended that learners already prossess skills from prerequisite course.

Notice that no prior knowledge of task, concept, or technology is assumed or required.

== Classroom environment

Describe the classroom environment, especially if it's on ROLE.

////
Uncomment and fill if sharing a ROLE classroom with other quick courses

=== For Red Hat associates and partners

If you are a Red Hat associate or partner, you must first enroll in the virtual classroom lab, by using one of the following links:

* https://training-lms.redhat.com/sso/saml/auth/rhlpint?RelayState=deeplinkoffering=84932767[HOL019 for Red Hat associates^] on the Red Hat Learning Portal
* https://training-lms.redhat.com/sso/saml/auth/rhopen?RelayState=deeplinkoffering=84932768[HOL019 for Red Hat partners^] on Red Hat Partner Connect

After you enroll to HOL019 once, you can use the following links for subsequent access to the virtual classroom lab directly on Red Hat Online Learning (ROLE):

* https://role.rhu.redhat.com/rol-rhu/app/courses/hol019-10.0/[HOL019 for Red Hat associates^] on ROLE
* https://rol.redhat.com/rol/app/courses/hol019-10.0/[HOL019 for Red Hat partners^] on ROLE

=== For Red Hat customers

If you are a Red Hat customer with a *Red Hat Learning Subscription*, you can use the following link to access the virtual classroom lab on Red Hat Online Learning (ROLE):

* https://rol.redhat.com/rol/app/courses/hol019-10.0/[HOL019 for Red Hat customers^] with a *Red Hat Learning Subscription*.

=== For all learners

After you enter HOL019 on ROLE, follow the instructions there to create a new course classroom lab and access its virtual machines (VMs).
If you already created a HOL019 classroom for another image mode with Red Hat Device Edge quick course, you can continue using the same classroom lab.

Be aware that ROLE classrooms have timers after which classroom labs are stopped and deleted, to conserve compute resources.
If you plan to use the same classroom lab for multiple Red Hat Device Edge quick courses, do not wait too long to continue.

You do not need to use the same classroom for multiple courses: each course provides step-by-step instructions to start from either a new classroom lab or to continue from an existing classroom lab.

You will follow this quick course by alternating between two browser windows: one to navigate quick course materials, such as this page; and another to access the virtual classroom lab environment, to perform hands-on activities.

If you can provision your own RHEL servers or VMs, it should be possible to configure all that is required for the hands-on activities by using a https://developers.redhat.com/products/rhel/download[free subscription^] from the https://developers.redhat.com/about[Red Hat Developer Program^], which gives access to RHEL installation media and RHEL package repositories.

=== About Red Hat Online Learning (ROLE) and Red Hat Learning Subscription

The Red Hat Online Learning (ROLE) website provides https://www.redhat.com/en/services/training-and-certification[Red Hat Training and Certification^] course materials and their virtual classroom labs.
You must be enrolled in a Red Hat Training course or subscription to have access to ROLE as a Red Hat customer.

A basic https://www.redhat.com/en/services/training/learning-subscription[Red Hat Learning Subscription^] offers access to a number of Red Hat Training courses and virtual classroom lab time.
Higher subscription tiers offer additional benefits, such as Red Hat Certification Exam vouchers.
////

== Other sources of information about Product

For documentation about Product, see either its https://docs.redhat.com/en/documentation/TBD[product documentation^] or its https://github.com/TBD[upstream project documentation^].

== Author

*Fernando Lozano* +
Training Content Architect +
Red Hat - Product Portfolio Marketing & Learning

////
Special thanks to people for their support while designing and writing this course.
////